### ISSUE TITLE
Today @ NOI: add subtitle and little improvements

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events-today-noi#1]
As NOI Meeting management I want that the subtitle of an event (if present) and the right link to the room on maps is shown, to let the NOI visitor find the event they are looking for.

The task to complete this issue are:

- [x] Add the subtitle (if present) of an event;
- [x] If the organizator is displayed in two lines, reduce the space between the space between the two lines. Use the same spacing as for the Title of the event (see image below).
![Outlook-1cgbooih](https://github.com/noi-techpark/webcomp-events-today/assets/7909989/81718748-d0ec-42f3-842f-95505bde8f3e)
- [x] Show the right link to the room in maps.noi.bz.it;
- [x] Integrate the Web Component in today.noi.bz.it.

**Information to add Subtitle**

The font to be used are the following:
- _Titel_: Source Sans Pro Semibold | black (font size same as the actual version)
- _Subtitel_: Source Sans Pro Regular | black (font size same as the Organizator in the actual version)
- _Organisator_: Source Sans Pro Bold | gray (font size same as the actual version)

The space between the Subtitle and the Organizator should be double of the one between the Title and Subtitle.
![image](https://github.com/noi-techpark/webcomp-events-today/assets/7909989/22e8e597-2acc-40e7-98ef-36bcd469a644)

**Information for the link in maps**

In the actual version of the web component, if you click on the Room link the home of maps get opened:

https://maps.noi.bz.it/en/

The expected behavieour is that the link to the right room should be opened. As for example, for an event taking place in the Seminar Room 1 the following link should be opened:

https://maps.noi.bz.it/en/?shared=A1--1-02&lang=en

**Comment by dulvui** [comment]
@sseppi All fixes are now implemented and the webcomponent has been moved to a own repository https://github.com/noi-techpark/webcomp-events-today-noi
Now in testing, today@eurac and today@noi have own webcomponents.

I also added a dev mode, where a multi line placeholder title, subtitle and company is visible, to see how it looks with multi line texts. It can be turned on by setting the devMode falg to true in the webcomp config.

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/events-today-noi

The webcomp is now also integrated in https://today.noi.testingmachine.eu

On https://today.noi.bz.it/ on the bottom right in the footer, there is a button with advanced features like filtering the events for company, room or technology field. Should I try to reproduce this features also in the webcomponent?

**Comment by dulvui** [comment]
@sseppi I added now also the special use cases for our displays displaying the website, like the half screen in the Foyer

**Default**
https://today.noi.testingmachine.eu
**Foyer** with black header, dateTime instead of NOI logo and half screen
https://today.noi.testingmachine.eu/?location=foyer
**D1** with black header, dateTime instead of NOI logo and full screen
https://today.noi.testingmachine.eu/?location=D1

**Comment by sseppi** [comment]
@dulvui 

I hade the opportunity to test the component with our Meeting Management and Communication department. I got the OK from both sides to put the component online on production.

**Comment by dulvui** [comment]
@sseppi Great news! I will publish the web component in production next week.
I still need to integrate it also on the website, and that will take some hours, but should be quite quick. I just need to pass the URL parameters to the webcomponent with a small JS script.

**Comment by dulvui** [comment]
Everything works now and is visible correctly on the displays in the Foyer.
https://today.noi.bz.it uses now the webcomponent
